[package]
name = "midgarts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
chrono = "0.4.23"
dotenv = "0.15.0"
log = "0.4.17"
pretty_env_logger = "0.4.0"
